title: Xiaoyang Wang
logo: Xiaoyang Wang.png
description: M.S. student in Xi'an Jiaotong University.
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins: 
- jekyll-remote-theme 

